# Site settings
title: Eunji Briller Kim
email: brillerkim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Eunji Briller Kim
  
  howtounit
  청주공예비엔날레
  Cheongju International Craft Biennale
  
  brillerkim@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brillerkim.github.io/" # the base hostname & protocol for your site
twitter_username: brillerkim
github_username:  brillerkim

# Build settings
markdown: kramdown
permalink: pretty